### ISSUE TITLE
Got OrientDB 2.0.1 while orientdb_version set to 2.2.22

### ISSUE THREAD

**Issue by asyd** [migibert/orientdb-role#24]
Hi,

I want to use this role to install OrientDB 2.2.22, there the part of playbook I used:

```
  vars:
    orientdb_version: 2.2.22
    orientdb_enable_distributed: true
    orientdb_distributed:
      hazelcast_network_port: 2434
      hazelcast_group: orientdb
      hazelcast_password: orientdb
      multicast_enabled: False
      tcp_enabled: True
      tcp_members:
        - 172.21.71.5
        - 172.21.71.8
  roles:
    - { role: orientdb-role, tags: ["orientdb"] }
```

However the version 2.0.1 is still installed
