### ISSUE TITLE
orientdb_path doesn't change extracted directory

### ISSUE THREAD

**Issue by CodeLenny** [migibert/orientdb-role#25]
Hi,
I found that `orientdb_dir` and `orientdb_path` don't play well together in terms of user customization.

I'd like to install OrientDB in `/opt/orientdb`, but `orientdb_path` doesn't change where the files are extracted - they are still extracted into `/opt/orientdb-community-{{orientdb_version}}`.

I'd like to change things so the extraction takes `orientdb_path` into account:

```yml
- name: Unarchive OrientDB tarball
  unarchive:
    copy: no
    src: "/tmp/orientdb-{{orientdb_version}}.tar.gz"
    dest: "/tmp"

- name: Move OrientDB files into the correct location
  vars:
    tmp_dir: /tmp/orientdb-community-{{orientdb_version}}
  command: mv {{tmp_dir}} {{orientdb_path}} creates={{orientdb_path}} removes={{tmp_dir}}
```

I'm planning to make this change and submit a PR.  Please let me know if you have any feedback.
